export const MAX_QUESTION_LENGTH = 150;
export const MAX_AFTER_YES_TITLE_LENGTH = 50;
export const MAX_AFTER_YES_DESCRIPTION_LENGTH = 200;
export const MAX_AFTER_YES_BUTTON_LENGTH = 40;
export const MAX_PROJECT_NAME_LENGTH = 30;
